apiVersion: apps/v1
kind: Deployment
metadata:
  name: iredmail-deployment
  labels:
    app: iredmail
    owner: vegor
    description: IredMail_post_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iredmail
  template:
    metadata:
      labels:
        app: iredmail
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx
          name: nfs-volume
          subPath: nginx
        - mountPath: /opt/www
          name: nfs-volume
          subPath: opt/www
        - mountPath: /etc/ssl
          name: nfs-volume
          subPath: ssl

      - name: php-fpm
        image: vegor/iredmail_php
#        ports:
#        - containerPort: 9999
        volumeMounts:
        - mountPath: /opt/www
          name: nfs-volume
          subPath: opt/www

      - name: dovecot
        image: vegor/iredmail_dovecot
#        ports:
#        - containerPort: 143
#        - containerPort: 995
#        - containerPort: 110
#        - containerPort: 993
        volumeMounts:
        - mountPath: /etc/dovecot
          name: nfs-volume
          subPath: dovecot
        - mountPath: /etc/ssl
          name: nfs-volume
          subPath: ssl
        - mountPath: /var/vmail
          name: nfs-volume
          subPath: vmail

      - name: amavis
        image: vegor/iredmail_amavis
#        ports:
#        - containerPort: 1024
#        - containerPort: 1026
#        - containerPort: 9998
        volumeMounts:
        - mountPath: /etc/amavis
          name: nfs-volume
          subPath: amavis
        - mountPath: /var/lib/dkim
          name: nfs-volume
          subPath: dkim

      - name: postfix
        image: vegor/iredmail_postfix
        ports:
        - containerPort: 25
#        - containerPort: 587
#        - containerPort: 10025
        volumeMounts:
        - mountPath: /etc/postfix
          name: nfs-volume
          subPath: postfix
        - mountPath: /etc/ssl
          name: nfs-volume
          subPath: ssl

      volumes:
      - name: nfs-volume
        nfs:
          server: 172.21.30.1
          path: /volume1/test-nfs
          readOnly: no

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: iredmail-deploy-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iredmail-autoscaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: iredmail
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30007
      protocol: TCP
  selector:
    app: iredmail
